name: ğŸ“¦ CI Workflow (on PR)


on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test-and-lint:
    name: "ğŸ§° Test & Lint"
    runs-on: ubuntu-latest
    outputs:
      PACKAGE_VERSION: ${{ steps.extract_version.outputs.PACKAGE_VERSION }}
    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v4
      - 
        name: âš™ï¸ Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - 
        name: âš™ï¸ Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - 
        name: âš™ï¸ Install dependencies
        run: |
          poetry install
      - 
        name: ğŸ—ï¸ Run linting with ruff
        run: |
          poetry run ruff check . --fix
      - 
        name: ğŸ—ï¸ Run tests
        run: |
          poetry run coverage run -m pytest
          poetry run coverage report -m
      - 
        name: ğŸ“¦ Export coverage HTML
        run: |
          poetry run coverage html -d coverage_html
      - 
        name: ğŸ“¦ Upload coverage HTML artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage_html
      -  
        name: ğŸ” Extract version from pyproject.toml
        id: extract_version
        run: |
          VERSION=$(grep -Po '(?<=^version = ")[^"]*' ./pyproject.toml)
          echo "PACKAGE_VERSION=$VERSION" >> $GITHUB_OUTPUT